/**
 * Models Index
 * 
 * Loads all Sequelize models and sets up associations.
 * This file is auto-generated by the import pattern below.
 * When adding a NEW model:
 *   1. Create the model file in this directory
 *   2. Add the require() and init() call below
 *   3. Add associations in the associations section
 * 
 * @module models
 */
const { Sequelize } = require('sequelize');
const config = require('../config/database');
const logger = require('../utils/logger');

const env = process.env.NODE_ENV || 'development';
const dbConfig = config[env];

const sequelize = new Sequelize(
  dbConfig.database,
  dbConfig.username,
  dbConfig.password,
  dbConfig
);

// Import model definitions
const DepartmentModel = require('./Department');
const UserModel = require('./User');
const EmployeeModel = require('./Employee');
const AttendanceModel = require('./Attendance');
const LeaveRequestModel = require('./LeaveRequest');

// Initialize models
const Department = DepartmentModel(sequelize, Sequelize.DataTypes);
const User = UserModel(sequelize, Sequelize.DataTypes);
const Employee = EmployeeModel(sequelize, Sequelize.DataTypes);
const Attendance = AttendanceModel(sequelize, Sequelize.DataTypes);
const LeaveRequest = LeaveRequestModel(sequelize, Sequelize.DataTypes);

// ---------------------------------------------------------------
// ASSOCIATIONS
// ---------------------------------------------------------------
// Department -> Employees (one-to-many)
Department.hasMany(Employee, {
  foreignKey: 'department_id',
  as: 'employees',
});
Employee.belongsTo(Department, {
  foreignKey: 'department_id',
  as: 'department',
});

// Employee self-referencing for manager hierarchy
Employee.belongsTo(Employee, {
  foreignKey: 'manager_id',
  as: 'manager',
});
Employee.hasMany(Employee, {
  foreignKey: 'manager_id',
  as: 'directReports',
});

// Employee -> Attendance (one-to-many)
Employee.hasMany(Attendance, {
  foreignKey: 'employee_id',
  as: 'attendanceRecords',
});
Attendance.belongsTo(Employee, {
  foreignKey: 'employee_id',
  as: 'employee',
});

// Employee -> LeaveRequests (one-to-many)
Employee.hasMany(LeaveRequest, {
  foreignKey: 'employee_id',
  as: 'leaveRequests',
});
LeaveRequest.belongsTo(Employee, {
  foreignKey: 'employee_id',
  as: 'employee',
});

// Approver (User) -> LeaveRequests (one-to-many)
User.hasMany(LeaveRequest, {
  foreignKey: 'approved_by',
  as: 'approvedLeaves',
});
LeaveRequest.belongsTo(User, {
  foreignKey: 'approved_by',
  as: 'approver',
});

// User -> Employee (one-to-one)
User.belongsTo(Employee, {
  foreignKey: 'employee_id',
  as: 'employee',
});
Employee.hasOne(User, {
  foreignKey: 'employee_id',
  as: 'user',
});

// ---------------------------------------------------------------
// EXPORT
// ---------------------------------------------------------------
const db = {
  sequelize,
  Sequelize,
  Department,
  User,
  Employee,
  Attendance,
  LeaveRequest,
};

// Test the database connection
sequelize
  .authenticate()
  .then(() => {
    logger.info('✓ Database connection established successfully');
  })
  .catch((err) => {
    logger.error('✗ Unable to connect to the database:', err);
  });

module.exports = db;
